'use strict';
/* Kanban — power-ups de relatórios e métricas, equipe e reuniões, importar/exportar e aparência. */

const feitosDe = q => S.cartoes.filter(c => c.quadro === q.id && c.feito && !c.lixo);
const diasDe = ms => ms / 864e5;
const mediana = (l, p) => { if (!l.length) return 0; const s = l.slice().sort((a, x) => a - x); return s[Math.min(s.length - 1, Math.floor(s.length * (p || .5)))]; };
const kpi = (n, r, cls) => `<div class="kpi ${cls || ''}"><b>${n}</b><small>${r}</small></div>`;
const semanasAtras = t => Math.floor((Date.now() - t) / (7 * 864e5));
const vazaoSemanal = (q, n) => [...Array(n)].map((_, i) => feitosDe(q).filter(c => semanasAtras(c.feito) === n - 1 - i).length);

// Fotografia diária do quadro (cartões por lista, abertos e pontos), usada pelo fluxo cumulativo e pelo burndown.
function fotografar(q) {
  const cs = vivos(q), l = {}; listasDe(q).forEach(x => { l[x.id] = cs.filter(c => c.lista === x.id).length; });
  const f = { l, ab: cs.filter(c => !c.feito).length, pts: soma(cs.filter(c => !c.feito), c => c.d.pts) }, s = q.d.snap = q.d.snap || {}, h = hoje();
  if (JSON.stringify(s[h]) === JSON.stringify(f)) return;
  s[h] = f;
  Object.keys(s).sort().slice(0, -120).forEach(k => delete s[k]);
  salvarQ(q, true); DB.persist();
}
const fotoAo = { abrir(q) { fotografar(q); }, criar(c, q) { setTimeout(() => fotografar(q), 0); }, mover(c, de, para, q) { setTimeout(() => fotografar(q), 0); }, concluir(c, q) { setTimeout(() => fotografar(q), 0); }, ligar(q) { fotografar(q); } };
// Série contínua de dias entre a primeira foto e hoje, repetindo a última foto conhecida nos dias sem registro.
function serieFotos(q, desde) { const s = q.d.snap || {}, ks = Object.keys(s).sort().filter(k => !desde || k >= desde); if (!ks.length) return []; const out = []; let ult = s[ks[0]]; for (let d = ks[0]; d <= hoje(); d = mais(d, 1)) { if (s[d]) ult = s[d]; out.push([d, ult]); } return out; }

/* ===== Relatórios e métricas ===== */
PUP({ id: 'cfd', cat: 'metricas', icone: '🌊', nome: 'Fluxo cumulativo (CFD)', desc: 'O gráfico clássico do Kanban: quantos cartões havia em cada etapa, dia após dia. Faixas que engordam mostram onde o trabalho está acumulando.',
  ao: fotoAo,
  ferramentas: q => [['Diagrama de fluxo cumulativo', () => mostrar('🌊 Fluxo cumulativo', () => { fotografar(q); const s = serieFotos(q).slice(-60), ls = listasDe(q).slice().reverse(), pal = ['#2FA05A', '#1BA39C', '#2D7DD2', '#5B6CF0', '#8B5CF6', '#D6489A', '#F08A24', '#E8B81F', '#8A6A4F', '#6B7280']; return s.length < 2 ? `<p class="vazio">O gráfico começa a se formar amanhã: o Kanban guarda uma fotografia do quadro por dia.<br>Hoje: ${ls.map(l => esc(l.nome) + ' ' + ((s[0] || [0, { l: {} }])[1].l[l.id] || 0)).join(' · ')}</p>` : G.linhas(ls.map((l, i) => ({ nome: l.nome, cor: l.cor || pal[i % pal.length], pts: s.map(x => x[1].l[l.id] || 0) })), s.map(x => fData(x[0])), { area: true, w: 720, h: 300 }) + '<p class="dica">De baixo para cima, da última etapa à primeira. A distância horizontal entre as faixas é o tempo de travessia; a vertical, o trabalho em andamento.</p>'; })]] });

PUP({ id: 'burndown', cat: 'metricas', icone: '📉', nome: 'Burndown', desc: 'Quanto trabalho ainda falta, dia a dia, contra a linha ideal até a data final. Conta cartões ou pontos de esforço.',
  cfg: [{ k: 'ini', rot: 'Início do período', tipo: 'data', val: '' }, { k: 'fim', rot: 'Data final', tipo: 'data', val: '' }, { k: 'por', rot: 'Medir em', tipo: 'lista', op: [['ab', 'Cartões em aberto'], ['pts', 'Pontos em aberto']], val: 'ab' }],
  ao: fotoAo,
  ferramentas: q => [['Gráfico de burndown', () => mostrar('📉 Burndown', () => { fotografar(q); const k = cfg('burndown', q), s = serieFotos(q, k.ini); if (!s.length) return '<p class="vazio">Sem dados no período.</p>'; const fim = k.fim && k.fim > s[0][0] ? k.fim : mais(s[0][0], 14), n = difDias(fim, s[0][0]) + 1, v0 = s[0][1][k.por] || 0, dias = [...Array(n)].map((_, i) => mais(s[0][0], i)); const real = dias.map((d, i) => s[i] ? s[i][1][k.por] || 0 : null).filter(x => x != null); return `<div class="kpis">${kpi(fNum(v0), 'no início')}${kpi(fNum(real[real.length - 1]), 'faltam hoje')}${kpi(Math.max(0, difDias(fim, hoje())), 'dias até ' + fData(fim))}</div>` + G.linhas([{ nome: 'Ideal', cor: '#9aa3af', trac: true, pts: dias.map((_, i) => v0 * (1 - i / (n - 1))) }, { nome: 'Real', cor: '#E0483C', pts: real }], dias.map(d => fData(d)), { w: 720, h: 280 }) + `<p class="dica">${k.fim ? '' : 'Defina o início e a data final em ⚡ Power-ups › Burndown › Ajustar. '}Acima da linha tracejada, o ritmo está abaixo do necessário.</p>`; })]] });

PUP({ id: 'lead', cat: 'metricas', icone: '⏲️', nome: 'Lead time e cycle time', desc: 'Quanto tempo um cartão leva da criação à entrega (lead) e do início do trabalho à entrega (cycle): média, mediana, percentil 85 e a distribuição.',
  ferramentas: q => [['Lead time e cycle time', () => mostrar('⏲️ Lead time e cycle time', () => { const fs = feitosDe(q).filter(c => c.feito > Date.now() - 90 * 864e5), lead = fs.map(c => diasDe(c.feito - c.criado)), cyc = fs.map(c => diasDe(c.feito - (c.d.ini || c.criado))); if (!fs.length) return '<p class="vazio">Nenhum cartão concluído nos últimos 90 dias.</p>'; const fx = [[0, 1, 'até 1d'], [1, 2, '1–2d'], [2, 4, '2–4d'], [4, 7, '4–7d'], [7, 14, '1–2 sem'], [14, 30, '2–4 sem'], [30, 1e9, '+30d']], md1 = l => fNum(soma(l, x => x) / l.length); return `<div class="kpis">${kpi(fs.length, 'entregas em 90 dias')}${kpi(md1(lead) + 'd', 'lead time médio')}${kpi(fNum(mediana(lead)) + 'd', 'lead mediano')}${kpi(fNum(mediana(lead, .85)) + 'd', '85% entregues em até')}${kpi(md1(cyc) + 'd', 'cycle time médio')}${kpi(fNum(mediana(cyc, .85)) + 'd', 'cycle p85')}</div><h3>Distribuição do lead time</h3>${G.barras(fx.map(f => [f[2], lead.filter(x => x >= f[0] && x < f[1]).length]))}<p class="dica">Use o percentil 85 para prometer prazos: “entregamos em até ${fNum(mediana(lead, .85))} dias, 85% das vezes”.</p>`; })]] });

PUP({ id: 'vazao', cat: 'metricas', icone: '🚿', nome: 'Vazão semanal', desc: 'Quantos cartões foram concluídos por semana nas últimas doze semanas, com a média. A base para qualquer previsão.',
  ferramentas: q => [['Vazão (throughput) por semana', () => mostrar('🚿 Vazão semanal', () => { const v = vazaoSemanal(q, 12), m = soma(v, x => x) / 12; return `<div class="kpis">${kpi(fNum(m), 'média por semana')}${kpi(Math.max(...v), 'melhor semana')}${kpi(v[11], 'esta semana')}${kpi(soma(v, x => x), 'em 12 semanas')}</div>` + G.barras(v.map((n, i) => [i === 11 ? 'agora' : '-' + (11 - i) + 's', n, i === 11 ? 'var(--aviso)' : 'var(--pri)'])); })]] });

PUP({ id: 'previsao', cat: 'metricas', icone: '🔮', nome: 'Previsão (Monte Carlo)', desc: 'Quando o que está em aberto fica pronto? Simula milhares de futuros com base na sua vazão real e responde com probabilidades, não com chutes.',
  ferramentas: q => [['Quando termina? (previsão)', () => mostrar('🔮 Previsão de conclusão', () => { const v = vazaoSemanal(q, 10), n = vivos(q).filter(c => !c.feito).length; if (!n) return '<p class="vazio">Não há nada em aberto. 🎉</p>'; if (soma(v, x => x) < 3) return '<p class="vazio">Ainda não há histórico suficiente: conclua pelo menos três cartões para o Kanban conhecer o seu ritmo.</p>'; const res = []; for (let i = 0; i < 3000; i++) { let r = n, s = 0; while (r > 0 && s < 520) { r -= v[Math.floor(Math.random() * v.length)]; s++; } res.push(s); } const p = x => mediana(res, x), dia = s => fData(mais(hoje(), s * 7)), h = {}; res.forEach(s => { h[s] = (h[s] || 0) + 1; }); const ks = Object.keys(h).map(Number).sort((a, x) => a - x).slice(0, 16); return `<p class="dica">${n} cartões em aberto · vazão das últimas 10 semanas: ${v.join(', ')} · 3.000 simulações</p><div class="kpis">${kpi(dia(p(.5)), '50% de chance (' + p(.5) + ' sem)')}${kpi(dia(p(.85)), '85% de chance (' + p(.85) + ' sem)', 'bom')}${kpi(dia(p(.95)), '95% de chance (' + p(.95) + ' sem)')}</div><h3>Semanas até terminar</h3>${G.barras(ks.map(s => [s + 's', Math.round(h[s] / 30), s <= p(.85) ? 'var(--ok)' : 'var(--aviso)']))}<p class="dica">As barras mostram a porcentagem das simulações que terminaram em cada semana. Prometa a data dos 85%.</p>`; })]] });

PUP({ id: 'controle', cat: 'metricas', icone: '🎚️', nome: 'Gráfico de controle', desc: 'Cada entrega vira um ponto: quando terminou e quanto demorou. A linha da média e o limite superior separam o normal do que merece uma conversa.',
  ferramentas: q => [['Gráfico de controle', () => mostrar('🎚️ Gráfico de controle', () => { const fs = feitosDe(q).sort((a, x) => a.feito - x.feito).slice(-80); if (fs.length < 3) return '<p class="vazio">São necessárias pelo menos três entregas.</p>'; const ys = fs.map(c => diasDe(c.feito - (c.d.ini || c.criado))), m = soma(ys, x => x) / ys.length, dp = Math.sqrt(soma(ys, y => (y - m) ** 2) / ys.length), lim = m + 2 * dp, mx = Math.max(lim, ...ys) * 1.1 || 1, W = 720, H = 280, X = i => 40 + i * (W - 60) / Math.max(1, fs.length - 1), Y = v => H - v / mx * (H - 20); return `<svg class="graf" viewBox="0 0 ${W} ${H + 24}"><line x1="40" x2="${W - 10}" y1="${Y(m)}" y2="${Y(m)}" stroke="#2D7DD2" stroke-width="2"/><text x="${W - 12}" y="${Y(m) - 4}" text-anchor="end" class="gr">média ${fNum(m)}d</text><line x1="40" x2="${W - 10}" y1="${Y(lim)}" y2="${Y(lim)}" stroke="#E0483C" stroke-width="2" stroke-dasharray="6 5"/><text x="${W - 12}" y="${Y(lim) - 4}" text-anchor="end" class="gr">limite ${fNum(lim)}d</text><line x1="40" x2="${W}" y1="${H}" y2="${H}" class="ge"/><text x="36" y="${H}" text-anchor="end" class="gr">0</text><text x="36" y="${Y(mx) + 10}" text-anchor="end" class="gr">${fNum(mx)}d</text>${fs.map((c, i) => `<circle cx="${X(i)}" cy="${Y(ys[i])}" r="5" fill="${ys[i] > lim ? '#E0483C' : '#2FA05A'}"><title>${esc(c.titulo)}: ${fNum(ys[i])}d · ${fData(ymd(new Date(c.feito)))}</title></circle>`).join('')}</svg><p class="dica">Pontos vermelhos ficaram acima do limite (média + 2 desvios). Passe o mouse para ver o cartão.</p><div class="linhas">${fs.filter((c, i) => ys[i] > lim).map(c => linhaC(c)).join('')}</div>`; })]] });

function relatorioSemanal(q) {
  const h = hoje(), s = Date.now() - 7 * 864e5, cs = S.cartoes.filter(c => c.quadro === q.id && !c.lixo), fe = cs.filter(c => c.feito > s), cr = cs.filter(c => c.criado > s), ab = cs.filter(c => !c.feito && !c.arquivado), li = l => l.map(c => `- ${c.titulo}${c.prazo ? ' (' + fData(c.prazo) + ')' : ''}${mbs(c).length ? ' — ' + mbs(c).map(m => m.nome.split(' ')[0]).join(', ') : ''}`).join('\n') || '- nada';
  return `# ${q.nome} — semana até ${fData(h)}\n\n**${fe.length}** concluídos · **${cr.length}** criados · **${ab.length}** em aberto · **${ab.filter(atrasado).length}** vencidos\n\n## ✅ Concluídos na semana\n${li(fe)}\n\n## 🚧 Em andamento\n${li(ab.filter(c => emCurso(q).includes(c.lista)))}\n\n## ⚠️ Vencidos\n${li(ab.filter(atrasado))}\n\n## 📅 Próximos 7 dias\n${li(ab.filter(c => c.prazo >= h && c.prazo <= mais(h, 7)).sort((a, x) => a.prazo < x.prazo ? -1 : 1))}\n`;
}
PUP({ id: 'relatorio', cat: 'metricas', icone: '🗞️', nome: 'Relatório semanal', desc: 'Um resumo pronto da semana: o que foi concluído, o que está em andamento, o que venceu e o que vem aí. Copie em Markdown e cole no e-mail ou no grupo.',
  ferramentas: q => [['Relatório da semana', () => mostrar('🗞️ Relatório semanal', () => { const t = relatorioSemanal(q); return `<div class="md cx-graf">${md(t)}</div><div class="botoes">${b('📋 Copiar em Markdown', () => copiar(t), 'pri')}${b('⬇️ Baixar .md', () => baixar('relatorio-' + hoje() + '.md', t, 'text/markdown'))}</div>`; })]] });

PUP({ id: 'heatmap', cat: 'metricas', icone: '🟩', nome: 'Mapa de calor', desc: 'Um quadradinho por dia, mais verde quanto mais cartões você concluiu, nos últimos seis meses. Constância à vista.',
  ferramentas: q => [['Mapa de calor das conclusões', () => mostrar('🟩 Mapa de calor', () => { const pd = grupo(feitosDe(q), c => ymd(new Date(c.feito))), h = hoje(), ini = mais(h, -(26 * 7 + new Date().getDay())), cel = []; for (let d = ini; d <= h; d = mais(d, 1)) { const n = (pd[d] || []).length; cel.push(`<i data-n="${Math.min(4, n)}" title="${fData(d)}: ${n}"></i>`); } const tot = soma(Object.values(pd), l => l.length), dias = Object.keys(pd).filter(d => d >= ini).length; return `<div class="kpis">${kpi(dias, 'dias com entrega')}${kpi(tot, 'entregas no total')}${kpi((pd[h] || []).length, 'hoje')}</div><div class="heat">${cel.join('')}</div><p class="dica">Cada coluna é uma semana, de domingo a sábado.</p>`; }, 'medio')]] });

PUP({ id: 'gargalo', cat: 'metricas', icone: '🍾', nome: 'Detector de gargalo', desc: 'Mede quanto tempo os cartões ficam, em média, em cada etapa e aponta a mais lenta. É ali que vale a pena agir primeiro.',
  ferramentas: q => [['Onde está o gargalo?', () => mostrar('🍾 Gargalo', () => { const cs = S.cartoes.filter(c => c.quadro === q.id && !c.lixo), d = listasDe(q).filter(l => !l.feito).map(l => { const ts = cs.map(c => ((c.d.tl || {})[l.id] || 0) + (c.lista === l.id && !c.feito ? naFase(c) : 0)).filter(x => x > 0); return [l.nome, ts.length ? Math.round(diasDe(soma(ts, x => x) / ts.length) * 10) / 10 : 0, '', cs.filter(c => c.lista === l.id && !c.arquivado).length]; }), mx = Math.max(...d.map(x => x[1])); if (!mx) return '<p class="vazio">Ainda não há movimento suficiente para medir.</p>'; const pior = d.find(x => x[1] === mx); return `<p>A etapa mais lenta é <b>${esc(pior[0])}</b>: os cartões ficam em média <b>${fNum(mx)} dia(s)</b> ali, e há ${pior[3]} agora.</p><h3>Tempo médio por etapa (dias)</h3>${G.barras(d.map(x => [x[0], x[1], x[1] === mx ? 'var(--erro)' : 'var(--pri)']))}<p class="dica">Ideias: reduzir o limite de WIP da etapa anterior, dividir cartões grandes ou reforçar quem trabalha nessa fase.</p>`; })]] });

PUP({ id: 'placar', cat: 'metricas', icone: '🥇', nome: 'Placar da equipe', desc: 'Por pessoa: o que entregou nos últimos 30 dias, o que tem em aberto, o que está vencido e os pontos entregues.',
  ferramentas: q => [['Placar da equipe', () => mostrar('🥇 Placar da equipe', () => { const cs = S.cartoes.filter(c => c.quadro === q.id && !c.lixo), s = Date.now() - 30 * 864e5, l = membros().map(m => { const g = cs.filter(c => lst(c.membros).includes(m.id)), fe = g.filter(c => c.feito > s); return { m, fe: fe.length, ab: g.filter(c => !c.feito && !c.arquivado).length, ve: g.filter(c => atrasado(c) && !c.arquivado).length, pts: soma(fe, c => c.d.pts) }; }).sort((a, x) => x.fe - a.fe); return l.length ? `<table class="tab"><thead><tr><th></th><th>Pessoa</th><th>Entregas (30d)</th><th>Pontos</th><th>Em aberto</th><th>Vencidos</th></tr></thead><tbody>${l.map((x, i) => `<tr><td>${['🥇', '🥈', '🥉'][i] || i + 1}</td><td>${avatar(x.m)} ${esc(x.m.nome)}</td><td><b>${x.fe}</b></td><td>${fNum(x.pts)}</td><td>${x.ab}</td><td class="${x.ve ? 'erro' : ''}">${x.ve}</td></tr>`).join('')}</tbody></table>` : '<p class="vazio">Cadastre membros no menu ⋯ do quadro.</p>'; })]] });

/* ===== Equipe e reuniões ===== */
PUP({ id: 'reacoes', cat: 'equipe', icone: '😀', nome: 'Reações nos comentários', desc: 'Responda a um comentário com um emoji em vez de escrever “ok”. Um clique põe, outro tira.',
  comentario: x => { const r = x.d.r || {}, eu0 = quemSou(), tg = e => () => { const l = r[e] = r[e] || []; if (l.includes(eu0)) tirar(l, eu0); else l.push(eu0); if (!l.length) delete r[e]; x.d.r = r; Data.put('comentarios', x); R(); }; return `<div class="reacoes">${Object.keys(r).map(e => `<button class="${r[e].includes(eu0) ? 'on' : ''}" ${on(tg(e))}>${e} ${r[e].length}</button>`).join('')}${['👍', '❤️', '🎉', '😄', '👀', '✅'].filter(e => !r[e]).map(e => `<button class="mais" ${on(tg(e))}>${e}</button>`).join('')}</div>`; } });

const Avisos = { l: (() => { try { return JSON.parse(localStorage.getItem('kanban-avisos')) || []; } catch (e) { return []; } })(), add(c, x) { Avisos.l.unshift({ t: Date.now(), x, c: c.id, n: c.titulo, novo: 1 }); Avisos.l = Avisos.l.slice(0, 60); Avisos.grava(); }, grava() { try { localStorage.setItem('kanban-avisos', JSON.stringify(Avisos.l)); } catch (e) {} } };
PUP({ id: 'observar', cat: 'equipe', icone: '👁️', nome: 'Observar cartões', desc: 'Siga os cartões que importam. Um sino no topo junta o que aconteceu com eles: mudanças de etapa, conclusões, comentários e prazos chegando.',
  selo: c => c.d.obs ? '<span class="selo neutro" title="Você observa este cartão">👁</span>' : '',
  lateral: c => lat(c.d.obs ? '👁️ Deixar de observar' : '👁️ Observar', () => { c.d.obs = !c.d.obs; salvar(c); R(); }),
  barra: () => { const n = Avisos.l.filter(a => a.novo).length; return `<button class="tb ${n ? 'on' : ''}" ${on(() => { mostrar('🔔 Avisos dos cartões observados', () => `<div class="linhas">${Avisos.l.map(a => `<button class="linha" ${on(() => { const c = byId(S.cartoes, a.c); if (c) { Dlg.fechar(); abrirCartao(c); } })}><small style="min-width:90px">${fQuando(a.t)}</small><span>${esc(a.x)}</span><b>${esc(a.n)}</b></button>`).join('') || '<p class="vazio">Nenhum aviso. Abra um cartão e clique em “Observar”.</p>'}</div><div class="botoes">${b('Limpar avisos', () => { Avisos.l = []; Avisos.grava(); R(); })}</div>`, 'medio'); Avisos.l.forEach(a => { delete a.novo; }); Avisos.grava(); })} title="Avisos">🔔${n ? ' <span>' + n + '</span>' : ''}</button>`; },
  ao: { mover(c, de, para) { if (c.d.obs) Avisos.add(c, 'Foi para ' + para.nome); }, concluir(c) { if (c.d.obs) Avisos.add(c, 'Concluído'); }, comentar(c, t) { if (c.d.obs) Avisos.add(c, 'Comentário: ' + t.slice(0, 60)); },
    minuto(q) { const am = mais(hoje(), 1); vivos(q).forEach(c => { if (c.d.obs && !c.feito && c.prazo && c.prazo <= am && c.d.obsAv !== c.prazo) { c.d.obsAv = c.prazo; salvar(c, true); Avisos.add(c, c.prazo < hoje() ? 'Prazo vencido' : c.prazo === hoje() ? 'Vence hoje' : 'Vence amanhã'); DB.changed(); R.depois(); } }); } } });

PUP({ id: 'historico', cat: 'equipe', icone: '🕰️', nome: 'Histórico do cartão', desc: 'Na ficha, a linha do tempo do cartão: quando foi criado, por onde passou, quem assumiu, quando mudou o prazo e quando foi concluído.',
  secao: c => (c.d.h || []).length ? sec('🕰️ Histórico', `<div class="hist">${c.d.h.slice().reverse().map(h => `<div><b>${fQuando(h.t)}</b> · ${esc(h.x)}</div>`).join('')}</div>`) : '' });

PUP({ id: 'enquete', cat: 'equipe', icone: '🗳️', nome: 'Enquete no cartão', desc: 'Uma pergunta com opções dentro do cartão. Cada pessoa vota e as barras mostram o resultado na hora.',
  selo: c => c.d.enq ? `<span class="selo neutro">🗳️ ${soma(c.d.enq.ops, o => o.v.length)}</span>` : '',
  lateral: c => c.d.enq ? '' : lat('🗳️ Enquete…', async () => { const v = await pedir('Nova enquete', [{ k: 'p', rot: 'Pergunta' }, { k: 'o', rot: 'Opções (uma por linha)', tipo: 'area', linhas: 4 }], { ok: 'Criar' }); const ops = v ? v.o.split('\n').map(x => x.trim()).filter(Boolean) : []; if (v && v.p && ops.length > 1) { c.d.enq = { p: v.p, ops: ops.map(t => ({ t, v: [] })) }; salvar(c); R(); } else if (v) toast('Escreva a pergunta e ao menos duas opções.'); }),
  secao(c) { const e = c.d.enq; if (!e) return ''; const tot = soma(e.ops, o => o.v.length) || 1, eu0 = quemSou(); return sec('🗳️ ' + esc(e.p), e.ops.map(o => `<div class="cki" style="cursor:pointer" ${on(() => { if (o.v.includes(eu0)) tirar(o.v, eu0); else { e.ops.forEach(x => tirar(x.v, eu0)); o.v.push(eu0); } salvar(c); R(); })}><span>${o.v.includes(eu0) ? '●' : '○'} ${esc(o.t)}</span><div class="barra" style="width:120px;margin:0"><i style="width:${o.v.length / tot * 100}%"></i></div><b>${o.v.length}</b></div>`).join(''), b('Excluir', () => { delete c.d.enq; salvar(c); R(); }, 'mini')); } });

PUP({ id: 'notas-quadro', cat: 'equipe', icone: '📝', nome: 'Notas do quadro', desc: 'Uma página de anotações para o quadro inteiro, com Markdown: objetivos, combinados, links úteis, ata da última reunião. No estilo de uma página do Notion.',
  barra: q => `<button class="tb" ${on(() => { let ed = !q.d.notas; mostrar('📝 Notas de ' + q.nome, () => ed ? `<textarea class="notas-q" data-k="notas-q" placeholder="# Objetivo do quadro\n\n- Combinados\n- Links úteis\n- [ ] Pendências">${esc(q.d.notas || '')}</textarea><div class="botoes">${b('Salvar', el => { q.d.notas = el.closest('#dlg').querySelector('textarea').value; salvarQ(q); ed = false; R(); }, 'pri')}</div>` : `<div class="md cx-graf">${md(q.d.notas, i => { q.d.notas = mdAlterna(q.d.notas, i); salvarQ(q); R(); })}</div><div class="botoes">${b('✎ Editar', () => { ed = true; R(); }, 'pri')}</div>`); })} title="Notas do quadro">📝</button>` });

const Daily = { i: 0, ini: 0 };
setInterval(() => { const e = $('#daily-r'); if (e) { const s = Math.max(0, Daily.seg - Math.floor((Date.now() - Daily.ini) / 1000)); e.textContent = pad(Math.floor(s / 60)) + ':' + pad(s % 60); e.style.color = s ? '' : '#E0483C'; } }, 500);
PUP({ id: 'daily', cat: 'equipe', icone: '🧍', nome: 'Reunião diária', desc: 'Conduz a daily em tela cheia: uma pessoa por vez, com o que concluiu desde ontem, o que tem em andamento, os bloqueios e um relógio para ninguém se alongar.',
  cfg: [{ k: 'seg', rot: 'Segundos por pessoa', tipo: 'numero', val: 90 }],
  ferramentas: q => [['Iniciar a reunião diária', () => { const ms = membros().filter(m => vivos(q).some(c => lst(c.membros).includes(m.id))); if (!ms.length) return toast('Atribua cartões aos membros para fazer a reunião.'); Daily.i = 0; Daily.ini = Date.now(); Daily.seg = cfg('daily', q).seg || 90;
    Dlg.abrir(() => { const m = ms[Daily.i], cs = vivos(q).filter(c => lst(c.membros).includes(m.id)), ont = Date.now() - 36 * 36e5, bloco = (t, l) => l.length ? `<h3 style="margin:14px 0 6px">${t}</h3><div class="linhas">${l.map(c => `<div class="linha"><b>${esc(c.titulo)}</b><small style="opacity:.7">${esc((byId(S.listas, c.lista) || {}).nome || '')}${c.d.bloq ? ' · ⛔ ' + esc(c.d.bloq) : ''}</small></div>`).join('')}</div>` : '';
      return `<div class="foco-t" style="position:static;justify-content:flex-start"><small>🧍 Reunião diária · ${Daily.i + 1} de ${ms.length}</small><h1>${avatar(m, 'g')} ${esc(m.nome)}</h1><div class="relogio" id="daily-r" style="font-size:54px">--:--</div><div style="width:100%;max-width:640px;text-align:left">${bloco('✅ Concluiu desde ontem', cs.filter(c => c.feito > ont))}${bloco('🚧 Em andamento', cs.filter(c => !c.feito && emCurso(q).includes(c.lista)))}${bloco('⛔ Bloqueios e atrasos', cs.filter(c => !c.feito && (c.d.bloq || atrasado(c))))}</div>
        <div class="fl">${Daily.i ? b('◀ Anterior', () => { Daily.i--; Daily.ini = Date.now(); R(); }) : ''}${Daily.i < ms.length - 1 ? b('Próximo ▶', () => { Daily.i++; Daily.ini = Date.now(); R(); }, 'pri') : b('Encerrar', () => Dlg.fechar(), 'pri')}</div></div>`; }, { classe: 'tela', vivo: true }); }]] });

const Poker = { v: {}, i: 0, ver: false };
PUP({ id: 'poker', cat: 'equipe', icone: '🃏', nome: 'Planning poker', desc: 'Estime em grupo sem um influenciar o outro: cada pessoa escolhe a sua carta em segredo, todas viram juntas e o resultado vai para os pontos do cartão.',
  lateral: c => lat('🃏 Planning poker', () => { Poker.v = {}; Poker.i = 0; Poker.ver = false; const ms = membros(), cartas = [0, 1, 2, 3, 5, 8, 13, 21, 34, '?'];
    mostrar('🃏 ' + c.titulo, () => { const aplicar = n => { c.d.pts = n; log(c, 'Estimado em ' + n + ' pontos'); salvar(c); Dlg.fechar(); R(); toast('Estimativa: ' + n + ' pontos'); };
      if (!ms.length) return `<p class="dica">Escolha a carta:</p><div class="poker">${cartas.filter(x => x !== '?').map(n => `<button ${on(() => aplicar(n))}>${n}</button>`).join('')}</div>`;
      if (!Poker.ver && Poker.i < ms.length) return `<p>${avatar(ms[Poker.i])} <b>${esc(ms[Poker.i].nome)}</b>, escolha a sua carta sem mostrar aos outros (${Poker.i + 1} de ${ms.length}):</p><div class="poker">${cartas.map(n => `<button ${on(() => { Poker.v[ms[Poker.i].id] = n; Poker.i++; if (Poker.i >= ms.length) Poker.ver = true; R(); })}>${n}</button>`).join('')}</div><div class="botoes">${b('Pular', () => { Poker.i++; if (Poker.i >= ms.length) Poker.ver = true; R(); })}</div>`;
      const ns = Object.values(Poker.v).filter(x => x !== '?'), med = ns.length ? soma(ns, x => x) / ns.length : 0, prox = cartas.filter(x => x !== '?').reduce((a, x) => Math.abs(x - med) < Math.abs(a - med) ? x : a, 0);
      return `<div class="poker">${ms.filter(m => Poker.v[m.id] != null).map(m => `<div style="text-align:center"><button class="on">${Poker.v[m.id]}</button><br><small>${esc(m.nome.split(' ')[0])}</small></div>`).join('')}</div><p style="margin-top:12px">Média <b>${fNum(med)}</b>${ns.length && Math.max(...ns) - Math.min(...ns) > 5 ? ' · <span class="erro">votos distantes: vale conversar e votar de novo</span>' : ''}</p><div class="botoes">${b('Usar ' + prox + ' pontos', () => aplicar(prox), 'pri')}${[...new Set(ns)].filter(n => n !== prox).map(n => b('Usar ' + n, () => aplicar(n))).join('')}${b('Votar de novo', () => { Poker.v = {}; Poker.i = 0; Poker.ver = false; R(); })}</div>`; }, 'medio'); }) });

PUP({ id: 'sorteio', cat: 'equipe', icone: '🎲', nome: 'Sorteador', desc: 'Na dúvida sobre o que fazer ou quem assume? Sorteie um cartão em aberto ou uma pessoa da equipe.',
  ferramentas: q => [['Sortear um cartão em aberto', () => { const cs = visiveis(q).filter(c => !c.feito); if (!cs.length) return toast('Nada em aberto.'); const c = cs[Math.floor(Math.random() * cs.length)]; toast('🎲 ' + c.titulo, 'Abrir', () => abrirCartao(c)); }], ['Sortear uma pessoa', () => { const ms = membros(); if (!ms.length) return toast('Cadastre membros primeiro.'); toast('🎲 ' + ms[Math.floor(Math.random() * ms.length)].nome); }]],
  lateral: c => S.membros.length > 1 ? lat('🎲 Sortear responsável', () => { const ms = membros(), m = ms[Math.floor(Math.random() * ms.length)]; c.membros = m.id; log(c, 'Sorteado para ' + m.nome); salvar(c); R(); toast('🎲 ' + m.nome); }) : '' });

function cartaoTexto(c, q, emMd) {
  const l = byId(S.listas, c.lista), n = emMd ? '**' : '';
  return (emMd ? '# ' : '') + c.titulo + '\n' + [`${n}Quadro:${n} ${q.nome} › ${l ? l.nome : ''}`, c.prazo && `${n}Prazo:${n} ${fData(c.prazo)}${c.hora ? ' ' + c.hora : ''}`, etq(c).length && `${n}Etiquetas:${n} ${etq(c).map(e => e.nome).join(', ')}`, mbs(c).length && `${n}Responsáveis:${n} ${mbs(c).map(m => m.nome).join(', ')}`].filter(Boolean).join('\n')
    + (c.texto ? '\n\n' + c.texto : '') + (c.d.ck || []).map(k => '\n\n' + (emMd ? '## ' : '') + k.nome + '\n' + k.itens.map(i => (emMd ? '- [' + (i.ok ? 'x' : ' ') + '] ' : (i.ok ? '☑ ' : '☐ ')) + i.t).join('\n')).join('');
}
PUP({ id: 'compartilhar', cat: 'equipe', icone: '📤', nome: 'Compartilhar cartão', desc: 'Mande o conteúdo do cartão para qualquer aplicativo do celular ou copie como texto ou Markdown, com descrição e checklists.',
  lateral: (c, q) => lat('📤 Compartilhar', el => menu(el, [navigator.share && ['Compartilhar com…', () => navigator.share({ title: c.titulo, text: cartaoTexto(c, q) }).catch(() => {})], ['Copiar como texto', () => copiar(cartaoTexto(c, q))], ['Copiar como Markdown', () => copiar(cartaoTexto(c, q, true))]])) });

/* ===== Importar, exportar e integrar ===== */
const csvCel = v => /[";\n,]/.test(String(v)) ? '"' + String(v).replace(/"/g, '""') + '"' : String(v);
function csvLer(t) { const sep = (t.split('\n')[0].match(/;/g) || []).length > (t.split('\n')[0].match(/,/g) || []).length ? ';' : ','; const out = []; let l = [], c = '', q = false; for (let i = 0; i < t.length; i++) { const ch = t[i]; if (q) { if (ch === '"' && t[i + 1] === '"') { c += '"'; i++; } else if (ch === '"') q = false; else c += ch; } else if (ch === '"') q = true; else if (ch === sep) { l.push(c); c = ''; } else if (ch === '\n') { l.push(c); out.push(l); l = []; c = ''; } else if (ch !== '\r') c += ch; } if (c || l.length) { l.push(c); out.push(l); } return out.filter(x => x.some(y => y.trim())); }
PUP({ id: 'csv', cat: 'dados', icone: '🧾', nome: 'Planilha (CSV)', desc: 'Exporte o quadro para abrir no Excel ou no Google Planilhas, com todos os campos, e importe cartões de uma planilha: título, lista, descrição, prazo e etiquetas.',
  ferramentas: q => [['Exportar CSV', () => { const fs = campos(q), cab = ['Número', 'Título', 'Lista', 'Descrição', 'Prazo', 'Etiquetas', 'Membros', 'Prioridade', 'Pontos', 'Valor', 'Concluído em', 'Criado em'].concat(fs.map(f => f.nome)), ls = listasDe(q); const linhas = vivos(q).sort((a, x) => ((byId(ls, a.lista) || {}).ordem - (byId(ls, x.lista) || {}).ordem) || a.ordem - x.ordem).map(c => [c.num, c.titulo, (byId(ls, c.lista) || {}).nome || '', c.texto, c.prazo, etq(c).map(e => e.nome).join(', '), mbs(c).map(m => m.nome).join(', '), c.prio ? PRIOS[c.prio] : '', c.d.pts || '', c.d.valor ? String(c.d.valor).replace('.', ',') : '', c.feito ? ymd(new Date(c.feito)) : '', ymd(new Date(c.criado))].concat(fs.map(f => (c.d.cf || {})[f.id] == null ? '' : c.d.cf[f.id]))); baixar(q.nome.replace(/[^\w\- ]+/g, '') + '.csv', '﻿' + [cab].concat(linhas).map(l => l.map(csvCel).join(';')).join('\r\n'), 'text/csv'); }],
    ['Importar CSV', async () => { const f = await lerArquivo('.csv,text/csv'); if (!f) return; const t = csvLer(f.dados.replace(/^﻿/, '')); if (t.length < 2) return toast('A planilha está vazia.'); const cab = t[0].map(x => semAcento(x.trim())), col = (...ns) => cab.findIndex(x => ns.includes(x)), it = col('titulo', 'title', 'name', 'nome', 'tarefa'), il = col('lista', 'list', 'etapa', 'status', 'fase'), id = col('descricao', 'description', 'desc'), ip = col('prazo', 'due', 'due date', 'data', 'vencimento'), ie = col('etiquetas', 'labels', 'tags', 'etiqueta'); if (it < 0) return toast('Não achei a coluna “Título”.'); let n = 0; t.slice(1).forEach(r => { const tit = (r[it] || '').trim(); if (!tit) return; const ln = il >= 0 ? (r[il] || '').trim() : ''; let l = ln && listasDe(q).find(x => semAcento(x.nome) === semAcento(ln)); if (!l && ln) l = Data.put('listas', { quadro: q.id, nome: ln, ordem: listasDe(q).length }, true); const pz = ip >= 0 ? (r[ip] || '').trim() : '', m = pz.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/); const c = criarCartao(q, l || listasDe(q)[0], tit, { texto: id >= 0 ? r[id] || '' : '', prazo: /^\d{4}-\d{2}-\d{2}/.test(pz) ? pz.slice(0, 10) : m ? m[3] + '-' + pad(+m[2]) + '-' + pad(+m[1]) : '' }); if (ie >= 0) { c.etiquetas = (r[ie] || '').split(',').map(x => etiquetaPorNome(q, x, true)).filter(Boolean).map(e => e.id).join(','); salvar(c, true); } n++; }); DB.changed(); R(); toast(n + ' cartões importados'); }]] });

const TRELLO_COR = { green: '#2FA05A', yellow: '#E8B81F', orange: '#F08A24', red: '#E0483C', purple: '#8B5CF6', blue: '#2D7DD2', sky: '#1BA39C', lime: '#57B26B', pink: '#D6489A', black: '#1F2937' };
function importarTrello(j) {
  if (!j || !Array.isArray(j.lists) || !Array.isArray(j.cards)) throw new Error('Este arquivo não é uma exportação do Trello.');
  const q = novoQuadro({ listas: [['_']], etiquetas: [] }, j.name || 'Quadro do Trello'), now = Date.now(), ml = {}, me = {};
  listasDe(q).forEach(l => Data.del('listas', l.id, true));
  if (j.desc) q.desc = j.desc;
  j.lists.forEach((l, i) => { ml[l.id] = Data.put('listas', { quadro: q.id, nome: l.name, ordem: l.pos || i, arquivada: !!l.closed, feito: /^(done|feito|conclu[ií]d[oa]s?|pronto)$/i.test(l.name.trim()) }, true); });
  (j.labels || []).forEach((e, i) => { me[e.id] = Data.put('etiquetas', { quadro: q.id, nome: e.name || e.color || 'Etiqueta', cor: TRELLO_COR[(e.color || '').split('_')[0]] || '#6B7280', ordem: i }, true); });
  const ck = grupo(j.checklists || [], k => k.idCard), com = (j.actions || []).filter(a => a.type === 'commentCard');
  j.cards.forEach((c, i) => { const l = ml[c.idList]; if (!l) return; q.d.seq++; const d = {}; if (ck[c.id]) d.ck = ck[c.id].map(k => ({ id: uid(), nome: k.name, itens: (k.checkItems || []).sort((a, x) => a.pos - x.pos).map(it => ({ id: uid(), t: it.name, ok: it.state === 'complete' })) })); const an = (c.attachments || []).filter(a => /^https?:/.test(a.url || '')).map(a => ({ id: uid(), nome: a.name || a.url, url: a.url })); if (an.length) d.an = an;
    const n = Data.put('cartoes', { quadro: q.id, lista: l.id, titulo: c.name, texto: c.desc || '', prazo: c.due ? ymd(new Date(c.due)) : '', inicio: c.start ? ymd(new Date(c.start)) : '', etiquetas: (c.idLabels || []).map(x => me[x] && me[x].id).filter(Boolean).join(','), ordem: c.pos || i, criado: now, entrou: now, arquivado: !!c.closed, feito: c.dueComplete || l.feito ? now : 0, num: q.d.seq, d }, true);
    com.filter(a => a.data && a.data.card && a.data.card.id === c.id).forEach(a => Data.put('comentarios', { cartao: n.id, texto: (a.memberCreator ? '**' + a.memberCreator.fullName + ':** ' : '') + a.data.text, criado: new Date(a.date).getTime() || now }, true)); });
  if (an_usa(q)) q.pups.anexos = true;
  salvarQ(q); return q;
}
const an_usa = q => S.cartoes.some(c => c.quadro === q.id && (c.d.an || []).length);
PUP({ id: 'trello', cat: 'dados', icone: '🟦', nome: 'Importar do Trello', desc: 'Traga um quadro inteiro do Trello: listas, cartões, descrições, etiquetas com as cores, prazos, checklists, links anexados e comentários. No Trello: menu › Imprimir, exportar e compartilhar › Exportar como JSON.',
  ferramentas: () => [['Importar quadro do Trello (.json)', async () => { const f = await lerArquivo('.json,application/json'); if (!f) return; try { const q = importarTrello(JSON.parse(f.dados)); abrirQuadro(q.id); toast('Quadro “' + q.nome + '” importado do Trello'); } catch (e) { toast(e.message || 'Não consegui ler o arquivo.'); } }]] });

const icsData = (d, h) => d.replace(/-/g, '') + (h ? 'T' + h.replace(':', '') + '00' : '');
PUP({ id: 'ics', cat: 'dados', icone: '🗓️', nome: 'Exportar para a agenda (.ics)', desc: 'Gera um arquivo de calendário com todos os prazos em aberto, para importar no Google Agenda, no Outlook ou no calendário do celular.',
  ferramentas: q => [['Exportar prazos (.ics)', () => { const cs = vivos(q).filter(c => c.prazo && !c.feito); if (!cs.length) return toast('Nenhum prazo em aberto.'); const e = s => String(s).replace(/([,;\\])/g, '\\$1').replace(/\n/g, '\\n'); baixar(q.nome.replace(/[^\w\- ]+/g, '') + '.ics', ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Kanban//PT-BR', 'CALSCALE:GREGORIAN'].concat(cs.flatMap(c => ['BEGIN:VEVENT', 'UID:' + c.id + '@kanban', 'DTSTAMP:' + new Date().toISOString().replace(/[-:]/g, '').slice(0, 15) + 'Z', c.hora ? 'DTSTART:' + icsData(c.prazo, c.hora) : 'DTSTART;VALUE=DATE:' + icsData(c.prazo), c.hora ? 'DURATION:PT1H' : 'DTEND;VALUE=DATE:' + icsData(mais(c.prazo, 1)), 'SUMMARY:' + e(c.titulo), 'DESCRIPTION:' + e(q.nome + ' › ' + ((byId(S.listas, c.lista) || {}).nome || '') + (c.texto ? '\n\n' + c.texto.slice(0, 600) : '')), 'END:VEVENT']), ['END:VCALENDAR']).join('\r\n'), 'text/calendar'); toast(cs.length + ' prazos exportados'); }]] });

PUP({ id: 'md-export', cat: 'dados', icone: '⬇️', nome: 'Exportar em Markdown', desc: 'O quadro inteiro como um documento de texto: uma seção por lista, uma caixinha por cartão, com prazos, etiquetas e checklists. Cola direto no Notion, no Obsidian ou no GitHub.',
  ferramentas: q => { const gera = () => `# ${q.nome}\n${q.desc ? '\n' + q.desc + '\n' : ''}` + listasDe(q).map(l => `\n## ${l.nome}\n\n` + (cruDaLista(l).map(c => `- [${c.feito ? 'x' : ' '}] **${c.titulo}**${c.prazo ? ' — ' + fData(c.prazo) : ''}${etq(c).length ? ' ' + etq(c).map(e => '`' + e.nome + '`').join(' ') : ''}${mbs(c).length ? ' @' + mbs(c).map(m => m.nome.split(' ')[0]).join(' @') : ''}` + (c.d.ck || []).flatMap(k => k.itens).map(i => `\n  - [${i.ok ? 'x' : ' '}] ${i.t}`).join('')).join('\n') || '_vazia_') + '\n').join(''); return [['Copiar o quadro em Markdown', () => copiar(gera())], ['Baixar o quadro em Markdown (.md)', () => baixar(q.nome.replace(/[^\w\- ]+/g, '') + '.md', gera(), 'text/markdown')]]; } });

const bkLer = q => { try { return JSON.parse(localStorage.getItem('kanban-bk-' + q.id)) || []; } catch (e) { return []; } };
PUP({ id: 'backup-auto', cat: 'dados', icone: '🛟', nome: 'Cópias diárias do quadro', desc: 'Uma vez por dia o Kanban guarda uma cópia do quadro neste aparelho e mantém as três últimas. Se algo der errado, restaure o quadro como estava naquele dia.',
  ao: { abrir(q) { const l = bkLer(q), h = hoje(); if (l[0] && l[0].d === h) return; l.unshift({ d: h, p: pacoteDe(q, true) }); while (l.length > 3) l.pop(); for (; l.length; l.pop()) { try { localStorage.setItem('kanban-bk-' + q.id, JSON.stringify(l)); break; } catch (e) {} } }, ligar(q) { this.abrir(q); } },
  ferramentas: q => [['Restaurar uma cópia diária', async () => { const l = bkLer(q); if (!l.length) return toast('Ainda não há cópias deste quadro.'); const v = await pedir('Restaurar cópia', [{ k: 'd', rot: 'Cópia de', tipo: 'lista', op: l.map(x => [x.d, fData(x.d) + ' · ' + x.p.cartoes.length + ' cartões']) }, { tipo: 'info', rot: 'A cópia volta como um quadro novo, ao lado do atual. Nada é apagado.' }], { ok: 'Restaurar' }); if (!v) return; const x = l.find(y => y.d === v.d); abrirQuadro(importarPacote(x.p, q.nome + ' (cópia de ' + fData(x.d) + ')').id); toast('Cópia restaurada como um quadro novo'); }]] });

PUP({ id: 'email', cat: 'dados', icone: '✉️', nome: 'Enviar por e-mail', desc: 'Abre o seu programa de e-mail com o cartão pronto no corpo da mensagem: título, etapa, prazo, descrição e checklists.',
  lateral: (c, q) => lat('✉️ Enviar por e-mail', () => { location.href = 'mailto:?subject=' + encodeURIComponent(c.titulo) + '&body=' + encodeURIComponent(cartaoTexto(c, q).slice(0, 1800)); }) });

PUP({ id: 'link', cat: 'dados', icone: '🔗', nome: 'Link direto do cartão', desc: 'Copia um endereço que abre o Kanban já no cartão. Cole em e-mails, documentos e em outros cartões para pular direto ao ponto.',
  lateral: c => lat('🔗 Copiar link', () => copiar(location.origin + location.pathname + '#q=' + c.quadro + '&c=' + c.id)) });

PUP({ id: 'gcal', cat: 'dados', icone: '📆', nome: 'Pôr no Google Agenda', desc: 'Um botão na ficha abre o Google Agenda com o evento preenchido: título, data, hora e descrição do cartão. Não precisa conectar nada.',
  lateral: (c, q) => c.prazo ? lat('📆 Google Agenda', () => { const a = icsData(c.prazo, c.hora), h2 = c.hora ? pad((+c.hora.slice(0, 2) + 1) % 24) + c.hora.slice(2) : '', z = c.hora ? icsData(+c.hora.slice(0, 2) === 23 ? mais(c.prazo, 1) : c.prazo, h2) : icsData(mais(c.prazo, 1)); window.open('https://calendar.google.com/calendar/render?action=TEMPLATE&text=' + encodeURIComponent(c.titulo) + '&dates=' + a + '/' + z + '&details=' + encodeURIComponent((q.nome + '\n\n' + c.texto).slice(0, 900)) + (c.d.local ? '&location=' + encodeURIComponent(c.d.local) : ''), '_blank', 'noopener'); }) : '' });

PUP({ id: 'texto-import', cat: 'dados', icone: '📄', nome: 'Importar de texto', desc: 'Cole um texto ou Markdown e ele vira quadro: linhas com # viram listas, linhas com - viram cartões e os itens recuados viram checklist. Ótimo para atas e planos escritos às pressas.',
  ferramentas: q => [['Importar de texto ou Markdown', async () => { const v = await pedir('Importar de texto', [{ k: 't', rot: 'Texto', tipo: 'area', linhas: 12, ph: '# A fazer\n- Comprar tinta\n  - branca\n  - rolo\n- Ligar para o pintor amanhã\n# Feito\n- Escolher as cores' }, { tipo: 'info', rot: 'Linhas com # criam (ou usam) uma lista. Cartões fora de qualquer # vão para a primeira lista.' }], { ok: 'Importar', classe: 'medio' }); if (!v || !v.t.trim()) return; let l = listasDe(q)[0], c = null, n = 0; v.t.split('\n').forEach(ln => { let m; if ((m = ln.match(/^#{1,6}\s+(.+)$/))) { const nome = m[1].trim(); l = listasDe(q).find(x => semAcento(x.nome) === semAcento(nome)) || Data.put('listas', { quadro: q.id, nome, ordem: listasDe(q).length }, true); c = null; } else if ((m = ln.match(/^\s{2,}(?:[-*•]|\d+[.)])\s+(?:\[( |x)\]\s+)?(.+)$/i)) && c) { const k = (c.d.ck = c.d.ck || [{ id: uid(), nome: 'Checklist', itens: [] }])[0]; k.itens.push({ id: uid(), t: m[2].trim(), ok: m[1] === 'x' || m[1] === 'X' }); salvar(c, true); } else if ((m = ln.match(/^(?:[-*•]|\d+[.)])\s+(?:\[( |x)\]\s+)?(.+)$/i)) || (ln.trim() && (m = [0, '', ln.trim()]))) { if (!l) l = Data.put('listas', { quadro: q.id, nome: 'A fazer', ordem: 0 }, true); c = criarCartao(q, l, m[2].replace(/\*\*/g, '')); if (m[1] === 'x' || m[1] === 'X') marcarFeito(c, true, true); n++; } }); DB.changed(); R(); toast(n + ' cartões importados'); }]] });

/* ===== Aparência e conforto ===== */
PUP({ id: 'fundos', cat: 'visual', icone: '🌄', nome: 'Fundos personalizados', desc: 'Doze degradês, qualquer cor sólida, uma imagem da internet ou uma foto sua como fundo do quadro.',
  ferramentas: q => [['Trocar o fundo do quadro', () => mostrar('🌄 Fundo do quadro', () => { const set = (css, img, k) => { q.d.fundoCss = css || ''; q.d.fundoImg = img || ''; if (k) q.fundo = k; salvarQ(q); R(); };
    return `<div class="fundos">${Object.entries(FUNDOS).map(([k, v]) => `<button class="${!q.d.fundoCss && !q.d.fundoImg && q.fundo === k ? 'on' : ''}" style="background:${v}" ${on(() => set('', '', k))}>${k}</button>`).join('')}</div><h3>Cor sólida</h3><div class="cores">${CORES.concat(['#0F766E', '#7C2D12', '#312E81', '#F4F5F7']).map(k => `<i style="background:${k};${q.d.fundoCss === k ? 'outline:3px solid var(--txt);outline-offset:2px' : ''}" ${on(() => set(k))}></i>`).join('')}<input type="color" value="${/^#/.test(q.d.fundoCss || '') ? q.d.fundoCss : '#1D5FB8'}" ${onC(v => set(v))}></div>
      <h3>Imagem</h3><div class="fl">${b('🌐 Por endereço…', async () => { const v = await pedir('Imagem de fundo', [{ k: 'u', rot: 'Endereço da imagem (https://…)', ph: 'https://' }]); if (v && /^https?:\/\//.test(v.u)) set('', v.u); })}${b('📷 Enviar foto…', async () => { const f = await lerArquivo('image/*', 'url'); if (f) { const u = await encolher(f.dados, 1500); if (u) set('', u); } })}${q.d.fundoImg ? b('Remover imagem', () => set('', '')) : ''}</div>`; }, 'medio')]] });

PUP({ id: 'densidade', cat: 'visual', icone: '↔️', nome: 'Densidade', desc: 'Compacto para ver mais cartões na tela, ou amplo para ler de longe e tocar com o dedo.',
  cfg: [{ k: 'modo', rot: 'Tamanho dos cartões', tipo: 'lista', op: [['denso', 'Compacto'], ['amplo', 'Amplo']], val: 'denso' }],
  classe: q => cfg('densidade', q).modo });

PUP({ id: 'largura', cat: 'visual', icone: '📐', nome: 'Largura e grade das listas', desc: 'Listas estreitas ou largas, e a opção de quebrar as listas em várias linhas em vez de rolar para o lado: o quadro inteiro numa tela só.',
  cfg: [{ k: 'larg', rot: 'Largura das listas', tipo: 'lista', op: [['', 'Normal'], ['estreito', 'Estreita'], ['largo-l', 'Larga']], val: 'estreito' }, { k: 'grade', tipo: 'caixa', rot: 'Quebrar as listas em linhas (sem rolagem lateral)', val: false }],
  classe: q => { const k = cfg('largura', q); return (k.larg || '') + (k.grade ? ' grade-l' : ''); } });

PUP({ id: 'daltonismo', cat: 'visual', icone: '👓', nome: 'Modo para daltônicos', desc: 'As etiquetas ganham texturas (listras, pontos, traços) além da cor, para serem distinguidas sem depender do tom.',
  classe: 'dalton' });

function confete() { const cores = ['#E0483C', '#F08A24', '#E8B81F', '#2FA05A', '#2D7DD2', '#8B5CF6', '#D6489A']; for (let i = 0; i < 46; i++) { const e = document.createElement('i'); e.className = 'confete'; e.style.left = Math.random() * 100 + 'vw'; e.style.background = cores[i % cores.length]; e.style.animationDuration = 1.3 + Math.random() * 1.4 + 's'; e.style.animationDelay = Math.random() * .3 + 's'; document.body.appendChild(e); setTimeout(() => e.remove(), 3200); } }
function plim() { try { const a = plim.c || (plim.c = new (window.AudioContext || window.webkitAudioContext)()); [660, 880, 1320].forEach((f, i) => { const o = a.createOscillator(), g = a.createGain(); o.frequency.value = f; o.type = 'sine'; g.gain.setValueAtTime(.0001, a.currentTime + i * .09); g.gain.exponentialRampToValueAtTime(.12, a.currentTime + i * .09 + .02); g.gain.exponentialRampToValueAtTime(.0001, a.currentTime + i * .09 + .25); o.connect(g).connect(a.destination); o.start(a.currentTime + i * .09); o.stop(a.currentTime + i * .09 + .3); }); } catch (e) {} }
PUP({ id: 'confete', cat: 'visual', icone: '🎉', nome: 'Confete ao concluir', desc: 'Uma chuva de confete e um som de vitória a cada cartão concluído. Porque terminar merece festa.',
  cfg: [{ k: 'som', tipo: 'caixa', rot: 'Tocar o som', val: true }, { k: 'conf', tipo: 'caixa', rot: 'Soltar o confete', val: true }],
  ao: { concluir(c, q) { const k = cfg('confete', q); if (Date.now() - (confete.t || 0) < 1500) return; confete.t = Date.now(); if (k.conf) confete(); if (k.som) plim(); } } });

PUP({ id: 'et-nome', cat: 'visual', icone: '🔤', nome: 'Etiquetas com nome', desc: 'Na frente dos cartões, as etiquetas mostram o nome escrito em vez de só a tirinha de cor.',
  classe: 'et-nome' });

PUP({ id: 'zen', cat: 'visual', icone: '🧘', nome: 'Modo zen', desc: 'Esconde menus, abas e botões e deixa só o quadro. Um botão discreto traz tudo de volta.',
  classe: () => U.zen ? 'zen' : '',
  barra: () => `<button class="zenb" ${on(() => { U.zen = !U.zen; if (U.zen) S.set.lado = false; R(); })} title="Modo zen">${U.zen ? '🧘 Sair do zen' : '🧘'}</button>` });

const ATALHOS = [['N', 'Novo cartão na primeira lista'], ['F ou /', 'Filtrar'], ['Q', 'Vista de quadro'], ['1–9', 'Trocar de vista'], ['P', 'Power-ups'], ['T', 'Ferramentas'], ['B', 'Mostrar ou esconder a barra lateral'], ['Ctrl+K', 'Paleta de comandos: ir a qualquer quadro, cartão ou ferramenta'], ['?', 'Esta ajuda'], ['Na ficha: C', 'Concluir ou reabrir'], ['Na ficha: E', 'Editar a descrição'], ['Na ficha: M', 'Atribuir a mim'], ['Esc', 'Fechar']];
function paleta(q) {
  U.pq = '';
  mostrar('Paleta de comandos', () => { const t = semAcento(U.pq), its = [];
    quadrosVivos().forEach(x => its.push([x.icone + ' Ir para ' + x.nome, () => abrirQuadro(x.id)]));
    if (q) { its.push(['📋 Vista: Quadro', () => { U.vista = 'quadro'; R(); }]); ativos(q).forEach(p => { if (p.vista) its.push([p.icone + ' Vista: ' + p.vista.nome, () => { U.vista = p.id; R(); }]); if (p.ferramentas) (p.ferramentas(q) || []).forEach(f => its.push([p.icone + ' ' + f[0], f[1]])); }); its.push(['⚡ Abrir os power-ups', () => galeria(q)]); if (t.length > 1) vivos(q).forEach(c => its.push(['🃏 ' + c.titulo, () => abrirCartao(c)])); }
    its.push(['🏠 Início', () => ir('inicio')], ['🔎 Buscar em tudo', () => ir('busca')], ['⚙️ Ajustes', () => ir('ajustes')]);
    const l = its.filter(i => !t || semAcento(i[0]).includes(t)).slice(0, 40);
    return `<input class="cheio" data-k="pq" placeholder="Digite um comando, quadro ou cartão…" value="${esc(U.pq)}" oninput="U.pq=this.value;R.depois()" ${onE(() => { if (l[0]) { Dlg.fechar(); l[0][1](); } })}><div class="cmd-l">${l.map(i => `<button class="item" ${on(() => { Dlg.fechar(); i[1](); })}>${esc(i[0])}</button>`).join('') || '<p class="vazio">Nada encontrado.</p>'}</div>`; }, 'medio');
  setTimeout(() => { const i = $('#dlg input'); if (i) i.focus(); }, 30);
}
document.addEventListener('keydown', e => {
  const q = U.tela === 'quadro' && Q();
  if (!q || !ativo('atalhos', q)) return;
  if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); if (!Dlg.pilha.length) paleta(q); return; }
  if (e.ctrlKey || e.metaKey || e.altKey || /^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName) || Dlg.pilha.length) return;
  const k = e.key.toLowerCase(), c = U.cartao && byId(S.cartoes, U.cartao);
  if (c) { if (k === 'c') { marcarFeito(c, !c.feito); R(); } else if (k === 'e') { Ficha.edit = 'texto'; U.foco = 'f-texto'; R(); } else if (k === 'm' && S.set.eu) { c.membros = alt(c.membros, S.set.eu); salvar(c); R(); } else return; e.preventDefault(); return; }
  const vs = ativos(q).filter(p => p.vista);
  if (k === 'n') { const l = listasDe(q).find(x => !x.fechada); if (l) { U.vista = 'quadro'; U.add = l.id; U.foco = 'add-' + l.id; R(); } }
  else if (k === 'f' || k === '/') popFiltro($('.topo .tb'), q), setTimeout(() => { const i = $('#pop input'); if (i) i.focus(); }, 30);
  else if (k === 'q') { U.vista = 'quadro'; R(); }
  else if (/^[1-9]$/.test(k) && vs[+k - 1]) { U.vista = vs[+k - 1].id; R(); }
  else if (k === 'p') galeria(q);
  else if (k === 't') ferramentas($('.topo .tb'), q);
  else if (k === 'b') { S.set.lado = !S.set.lado; DB.saveSet(); R(); }
  else if (k === '?') mostrar('⌨️ Atalhos de teclado', () => `<table class="tab"><tbody>${ATALHOS.map(a => `<tr><td style="white-space:nowrap"><span class="kbd">${a[0]}</span></td><td>${a[1]}</td></tr>`).join('')}</tbody></table>`, 'medio');
  else return;
  e.preventDefault();
});
PUP({ id: 'atalhos', cat: 'visual', icone: '⌨️', nome: 'Atalhos e paleta de comandos', desc: 'Use o quadro sem o mouse: N cria, F filtra, 1 a 9 trocam de vista, Ctrl+K abre a paleta que leva a qualquer quadro, cartão ou ferramenta. Aperte ? para ver todos.',
  ferramentas: q => [['Paleta de comandos (Ctrl+K)', () => paleta(q)], ['Ver os atalhos de teclado (?)', () => mostrar('⌨️ Atalhos de teclado', () => `<table class="tab"><tbody>${ATALHOS.map(a => `<tr><td style="white-space:nowrap"><span class="kbd">${a[0]}</span></td><td>${a[1]}</td></tr>`).join('')}</tbody></table>`, 'medio')]] });

PUP({ id: 'voz', cat: 'visual', icone: '🎤', nome: 'Ditado por voz', desc: 'Toque no microfone e fale a tarefa: o cartão é criado na primeira lista. Com a captura rápida ligada, “amanhã” e “sexta” viram o prazo.',
  barra: q => `<button class="tb" ${on(el => { const SR = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SR) return toast('Este navegador não tem reconhecimento de voz.'); const r = new SR(); r.lang = 'pt-BR'; r.interimResults = false; el.classList.add('on', 'pisca'); toast('🎤 Fale a tarefa…'); r.onresult = ev => { const t = ev.results[0][0].transcript.trim(); if (t) { const c = criarCartao(q, listasDe(q)[0], t[0].toUpperCase() + t.slice(1)); R(); toast('Criado: ' + c.titulo, 'Abrir', () => abrirCartao(c)); } }; r.onerror = ev => toast(ev.error === 'not-allowed' ? 'Permita o uso do microfone.' : 'Não entendi. Tente de novo.'); r.onend = () => el.classList.remove('on', 'pisca'); try { r.start(); } catch (e) {} })} title="Ditar um cartão">🎤</button>` });
